shop/src/Entity/CustomRoute.php
<?php


namespace App\Entity;

/**
 * Class CustomRoute
 * @Entity(tableName="route", repositoryClass="App\Repository\CustomRouteRepository")
 * @package App\Entity
 */
class CustomRoute extends AbstractEntity
{
    /**
     * @Entity\PrimaryKey()
     */
    protected $id;

    /**
     * @Entity\Column()
     */
    protected $short_url;

    /**
     * @Entity\Column()
     */
    protected $real_url;

    /**
     * @Entity\Column()
     */
    protected $name;
    /**
     * @Entity\Column()
     */
    protected $_left;

    /**
     * @Entity\Column()
     */
    protected $_right;

    /**
     * @Entity\Column()
     */
    protected $_lvl;

    /**
     * @Entity\Column()
     */
    protected $is_hidden;

    /**
     * @Entity\Column()
     */
    protected $params;

    /**
     * @Entity\ManyToOne(entity="App\Entity\Template", primary_key="template_id")
     */
    protected $template;

    /**
     * @Entity\ManyToOne(entity="App\Entity\Menu", primary_key="menu_id")
     */
    protected $menu;

    /**
     * @return int|null
     */
    public function getLeft(): ?int
    {
        return $this->_left;
    }

    /**
     * @param string $left
     */
    public function setLeft(string $left)
    {
        $this->_left = $left;
    }

    /**
     * @return int|null
     */
    public function getRight(): ?int
    {
        return $this->_right;
    }

    /**
     * @param string $right
     */
    public function setRight(string $right): void
    {
        $this->_right = $right;
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getShortUrl(): ?string
    {
        return $this->short_url;
    }

    /**
     * @param string $url
     */
    public function setShortUrl(string $url): void
    {
        $this->short_url = $url;
    }

    /**
     * @return string
     */
    public function getRealUrl(): ?string
    {
        return $this->real_url;
    }

    /**
     * @param string $url
     */
    public function setRealUrl(string $url): void
    {
        $this->real_url = $url;
    }

    /**
     * @return int|null
     */
    public function getLvl(): ?int
    {
        return $this->_lvl;
    }

    /**
     * @param int $lvl
     */
    public function setLvl(int $lvl)
    {
        $this->_lvl = $lvl;
    }

    /**
     * @return bool|null
     */
    public function getIsHidden(): ?bool
    {
        return $this->is_hidden == 1;
    }

    /**
     * @param bool $is_hidden
     */
    public function setIsHidden(bool $is_hidden)
    {
        $this->is_hidden = $is_hidden ? 1 : 0;
    }

    /**
     * @return mixed
     */
    public function getTemplate() : ?Template
    {
        return $this->template;
    }

    /**
     * @param Template|null $template
     */
    public function setTemplate(?Template $template): void
    {
        $this->template = $template;
    }

    /**
     * @return Menu|null
     */
    public function getMenu() : ?Menu
    {
        return $this->menu;
    }

    /**
     * @param Menu|null $menu
     */
    public function setMenu(?Menu $menu): void
    {
        $this->menu = $menu;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getParams(): ?string
    {
        return $this->params;
    }

    /**
     * @param string $params
     */
    public function setParams(string $params): void
    {
        $this->params = $params;
    }
}

shop/templates/custom_templates/base.form.html.twig
<form action="">
    {% if parent_route %}
        <input type="hidden" name="route[parent_id]" value="{{ parent_route.id }}">
    {% endif %}
    {% if route %}
        <input type="hidden" name="route[id]" value="{{ route.id }}">
    {% endif %}
    {% if template %}
        <input type="hidden" name="route[template_id]" value="{{ template.id }}">
    {% endif %}
    <div class="form-group">
        <label for="route[name]">Название страницы</label>
        <input type="text" class="form-control" name="route[name]" id="route[name]" value="{{ route.name }}">
    </div>
    <div class="form-group">
        <label for="route[short_url]">Адрес</label>
        <div class="d-inline-flex align-items-center">
            <input type="text" class="form-control" name="route[long_url]" id="route[long_url]"
                   value="{{ host }}{{ parent_route.realUrl }}/" disabled>
            <input type="text" class="form-control" name="route[short_url]" id="route[short_url]"
                   value="{{ route.shortUrl }}">
        </div>
    </div>
    {% include "custom_templates/base.form.vars.html.twig" %}

    <button class="btn btn-danger">{% if route %}Изменить{% else %}Добавить{% endif %}</button>
</form>

shop/templates/custom_templates/base.form.vars.html.twig
{% if vars %}
    {% for key,var in vars %}
        <div class="form-group">
            <label for="route[params][{{ key }}]">{{ var.title }}</label>
            {% if var.type == "text" %}

                {% if var.multiply %}
                    <span class="btn btn-sm btn-success" data-action="add" data-multiply="true" data-type="text"
                          data-name="route[params][{{ key }}][]"><i class="fa fa-plus"></i></span>
                    <div class="texts">
                        {% for text in params[key] %}
                            <div class="text-item item">
                                <input type="text" class="form-control" name="route[params][{{ key }}][]"
                                       value="{{ text }}">
                                <span class="btn btn-sm btn-danger" data-action="remove"><i
                                            class="fa fa-minus"></i></span>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="text" class="form-control" name="route[params][{{ key }}]" value="{{ params[key] }}">
                {% endif %}
            {% elseif var.type == "html" %}
                <div data-type="{{ var.type }}" name="route[params][{{ key }}]">{{ params[key]|raw }}</div>
            {% elseif var.type == "image" %}
                {% if var.multiply %}
                    <span class="btn btn-sm btn-success" data-action="add" data-multiply="true" data-type="image"
                          data-name="route[params][{{ key }}][]"><i class="fa fa-plus"></i></span>
                    <div class="images">
                        {% for image in params[key] %}
                            <div class="image-item item">
                                <img src="{{ image.path }}" width="30px" height="30px"
                                     alt=""><span class="name">{{ image.alias }}</span>
                                <input type="hidden" name="route[params][{{ key }}][]" value="{{ image.id }}">
                                <span class="btn btn-sm btn-danger" data-action="remove"><i
                                            class="fa fa-minus"></i></span>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <span class="btn btn-sm btn-primary" data-action="add" data-multiply="false" data-type="image"
                          data-name="route[params][{{ key }}]">Set</span>
                    {% set image = params[key] %}
                    {% if image %}
                        <div class="item image-item">
                            <img src="{{ image.path }}" width="30px" height="30px" alt=""><span
                                    class="name">{{ image.alias }}</span>
                            <input type="hidden" name="route[params][{{ key }}]" value="{{ image.id }}">
                            <span class="btn btn-sm btn-danger" data-action="remove"><i class="fa fa-minus"></i></span>
                        </div>
                    {% endif %}

                {% endif %}
            {% elseif var.type == "menu" %}
                <span class="btn btn-sm btn-primary" data-action="add" data-multiply="false" data-type="menu"
                      data-name="route[params][{{ key }}]">Set</span>
                {% set menu = params[key] %}
                {% if menu %}
                    <div class="menu-item item">
                        <span class="name">{{ menu.name }}</span>
                        <input type="hidden" name="route[params][{{ key }}]" value="{{ menu.id }}">
                        <span class="btn btn-sm btn-danger" data-action="remove"><i class="fa fa-minus"></i></span>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    {% endfor %}
{% endif %}

shop/templates/custom_templates/galery.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="wrapper" style="display: grid; grid-template-columns: 1fr 1fr 1fr 1fr; grid-gap: 10px">
    {{ text|raw }}
    {% for image in images %}
        <img src="{{ image.path }}" alt="">
    {% endfor %}
</div>
{% endblock %}

shop/templates/custom_templates/links.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="wrapper">
    {{ text|raw }}
    {% set routes = menu.routes %}
    {% for route in routes %}
      <div><a href="{{ route.realUrl }}">{{ route.name }}</a></div>
    {% endfor %}
</div>
{% endblock %}

shop/templates/custom_templates/page_with_text.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="wrapper">
        {{ text|raw }}
    </div>
{% endblock %}

shop/templates/custom_templates/text.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="wrapper">
    {% for tex in text %}
      <div>{{ tex }}</div>
    {% endfor %}
</div>
{% endblock %}

shop/templates/custom_templates/title.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <section class="main_slider">
        {% for image in slider %}
             <img src="{{ image.path }}" alt="">
        {% endfor %}
    </section>
    <section class="companies">
        <div class="wrapper">
            <ul>
                {% for brand in brands %}
                    <li><img src="{{ brand.path }}" alt=""></li>
                {% endfor %}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_1.jpg" alt=""></a></li>#}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_2.jpg" alt=""></a></li>#}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_3.jpg" alt=""></a></li>#}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_4.jpg" alt=""></a></li>#}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_5.jpg" alt=""></a></li>#}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_6.jpg" alt=""></a></li>#}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_7.jpg" alt=""></a></li>#}
{#                <li><a href="#!"><img src="/assets/design/images/dyn/brand_8.jpg" alt=""></a></li>#}
            </ul>
        </div>
    </section>
    {% if news %}
        <section class="slider">
            <div class="title">Новинки</div>
            <div class="wrapper">
                <div class="news_slider products">
                    {% for product in news %}
                        <div class="product_wrapper">
                            <div class="product " data-id="{{ product.id }}">
                                <div class="product_main">
                                    <div class="product_top">
                                        <div class="image">
                                            <div class="flags">
                                                {% for flag in product.flags %}
                                                    <div class="flag{% if flag.id == 1 %} sale {% endif %}{% if flag.id == 2 %} new {% endif %}{% if flag.id == 3 %} hit {% endif %}">{{ flag.name }}</div>
                                                {% endfor %}
                                            </div>
                                            <img src="{{ product.image.path }}" alt="">
                                        </div>
                                    </div>
                                    <div class="product_middle">
                                        <div class="product_name">
                                            <a href="/product/{{ product.id }}">{{ product.name }}</a>
                                        </div>
                                        <div class="product_buy">
                                            <span class="price">{{ product.price }} ТГ</span>
                                            <span class="buy_button">Купить</span>
                                        </div>
                                    </div>
                                </div>
                                <!--                        <div class="product_hide">-->
                                <!--                            <table class="product_params">-->
                                <!--                                <tr class="param">-->
                                <!--                                    <td >Материал упаковки</td>-->
                                <!--                                    <td class="value">Многослойный пакет</td>-->
                                <!--                                </tr>-->
                                <!--                                <tr class="param">-->
                                <!--                                    <td >Обжарка</td>-->
                                <!--                                    <td class="value">Средняя</td>-->
                                <!--                                </tr>-->
                                <!--                                <tr class="param">-->
                                <!--                                    <td >Особенности вкуса</td>-->
                                <!--                                    <td class="value">Кислинка</td>-->
                                <!--                                </tr>-->
                                <!--                            </table>-->
                                <!--                        </div>-->
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </section>
    {% endif %}
    <section class="about">
        <div class="wrapper">
            {{ about|raw }}
        </div>
    </section>
{% endblock %}